### ISSUE TITLE
Incompatibility with "Rotten Creatures" Mod

### ISSUE THREAD

**Issue by DEN-SNIPER** [Alexandra-Myers/Atlas-Combat-1.19#77]
(Warning, bad English ahead, read with cautious)
Combatify and Rotten Creatures prevent player from entering/creating world. % of world loading stuck at 100% and then some "unspeakable" (I mean "[Render thread/FATAL] Error executing task on Client" line that spams in logs) things starting to happen in logs on loop.

How it looks:
![изображение](https://github.com/Alexandra-Myers/Combatify/assets/47086772/5fea1454-b81b-4ea8-ad77-7f3969c4116a)
(not very impressive)

Log file:
[Logs.txt](https://github.com/user-attachments/files/15946103/Logs.txt)

**Comment by StunfMC** [comment]
Rotten Creatures only supports 1.19.2 and the version of Combatify for 1.19.2 is outdated. Most ofcompatibility issues have been fixed in newer versions, which is most likely why this is the case.

The only thing that I could say is to see if Rotten Creatures will update to 1.20.6 and try the latest version of Combatify. Otherwise, there is sadly nothing that we can do.

**Comment by StunfMC** [comment]
Rotten Creatures only supports 1.19.2 and the version of Combatify for 1.19.2 is outdated. Most of our compatibility issues have been fixed in newer versions, which is most likely why this is the case.

The only thing that I could say is to see if Rotten Creatures will update to 1.20.6 and try the latest version of Combatify. Otherwise, there is sadly nothing that we can do.
